# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

setPLINKobjInR <- function(t_bimFile, t_famFile, t_bedFile, t_SampleInModel) {
    invisible(.Call(`_POLMM_setPLINKobjInR`, t_bimFile, t_famFile, t_bedFile, t_SampleInModel))
}

setPOLMMobjInR <- function(t_muMat, t_iRMat, t_Cova, t_yVec, t_SPmatR, t_tau, t_printPCGInfo, t_tolPCG, t_maxiterPCG) {
    invisible(.Call(`_POLMM_setPOLMMobjInR`, t_muMat, t_iRMat, t_Cova, t_yVec, t_SPmatR, t_tau, t_printPCGInfo, t_tolPCG, t_maxiterPCG))
}

MAIN_REGION <- function(t_MarkerReqstd, t_NonZero_cutoff, t_StdStat_cutoff, t_maxMarkers, t_outputFile, t_missingRate_cutoff, t_maxMAF_cutoff) {
    .Call(`_POLMM_MAIN_REGION`, t_MarkerReqstd, t_NonZero_cutoff, t_StdStat_cutoff, t_maxMarkers, t_outputFile, t_missingRate_cutoff, t_maxMAF_cutoff)
}

rcpparma_hello_world <- function() {
    .Call(`_POLMM_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_POLMM_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_POLMM_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_POLMM_rcpparma_bothproducts`, x)
}

