# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

makeSeqMat <- function(t_n, t_J) {
    .Call(`_POLMM_makeSeqMat`, t_n, t_J)
}

updateSeqMat <- function(t_SeqMat, t_n1, t_J) {
    .Call(`_POLMM_updateSeqMat`, t_SeqMat, t_n1, t_J)
}

getStatVec <- function(t_SeqMat, t_GVec, t_muMat, t_iRMat) {
    .Call(`_POLMM_getStatVec`, t_SeqMat, t_GVec, t_muMat, t_iRMat)
}

getProb <- function(t_SeqMat, t_muMat) {
    .Call(`_POLMM_getProb`, t_SeqMat, t_muMat)
}

fitPOLMMcpp <- function(t_flagSparseGRM, t_flagGMatRatio, t_bimfile, t_famfile, t_bedfile, t_posSampleInPlink, t_Cova, t_yVec, t_beta, t_bVec, t_eps, t_tau, t_GMatRatio, t_SparseGRM, t_controlList) {
    .Call(`_POLMM_fitPOLMMcpp`, t_flagSparseGRM, t_flagGMatRatio, t_bimfile, t_famfile, t_bedfile, t_posSampleInPlink, t_Cova, t_yVec, t_beta, t_bVec, t_eps, t_tau, t_GMatRatio, t_SparseGRM, t_controlList)
}

setPOLMMGENEobj <- function(t_maxiterPCG, t_tolPCG, t_Cova, t_yVec, t_tau, t_SparseGRM, t_LOCOList, t_eta, t_nMaxNonZero) {
    invisible(.Call(`_POLMM_setPOLMMGENEobj`, t_maxiterPCG, t_tolPCG, t_Cova, t_yVec, t_tau, t_SparseGRM, t_LOCOList, t_eta, t_nMaxNonZero))
}

closePOLMMGENEobj <- function() {
    invisible(.Call(`_POLMM_closePOLMMGENEobj`))
}

setPOLMMGENEchr <- function(t_LOCOList, t_excludechr) {
    invisible(.Call(`_POLMM_setPOLMMGENEchr`, t_LOCOList, t_excludechr))
}

getStatVarS <- function(t_GMat, t_NonZero_cutoff, t_StdStat_cutoff) {
    .Call(`_POLMM_getStatVarS`, t_GMat, t_NonZero_cutoff, t_StdStat_cutoff)
}

getPvalERtoR <- function(t_GVec) {
    .Call(`_POLMM_getPvalERtoR`, t_GVec)
}

getobjP <- function(t_Cova, t_yMat, t_muMat, t_iRMat) {
    .Call(`_POLMM_getobjP`, t_Cova, t_yMat, t_muMat, t_iRMat)
}

outputadjGFast <- function(GVec, objP) {
    .Call(`_POLMM_outputadjGFast`, GVec, objP)
}

getyMatR <- function(yVec, n, J) {
    .Call(`_POLMM_getyMatR`, yVec, n, J)
}

